/**
 * Frontend copy of the ARK Color ID → { name, hex } map.
 * Mirrors backend/colorMap.js for use in React without a server round-trip.
 */
export const ARK_COLORS_FRONTEND = {
  0:   { name: 'Unset',                 hex: null },
  1:   { name: 'Red',                   hex: '#FF0000' },
  2:   { name: 'Blue',                  hex: '#233FFF' },
  3:   { name: 'Green',                 hex: '#1BFF2B' },
  4:   { name: 'Yellow',                hex: '#FFFF00' },
  5:   { name: 'Cyan',                  hex: '#00FFFF' },
  6:   { name: 'Magenta',               hex: '#FF00FF' },
  7:   { name: 'Light Gray',            hex: '#C0C0C0' },
  8:   { name: 'Dark Gray',             hex: '#808080' },
  9:   { name: 'Dark Red',              hex: '#8B0000' },
  10:  { name: 'Dark Blue',             hex: '#00008B' },
  11:  { name: 'Dark Green',            hex: '#006400' },
  12:  { name: 'Dark Yellow',           hex: '#9B870C' },
  13:  { name: 'Dark Cyan',             hex: '#008B8B' },
  14:  { name: 'Dark Magenta',          hex: '#8B008B' },
  15:  { name: 'Brown',                 hex: '#8B4513' },
  16:  { name: 'Orange',                hex: '#FF8C00' },
  17:  { name: 'Sky Blue',              hex: '#87CEEB' },
  18:  { name: 'Burnt Sienna',          hex: '#8B4513' },
  19:  { name: 'Vermillion',            hex: '#FF4500' },
  20:  { name: 'White',                 hex: '#FFFFFF' },
  21:  { name: 'Black',                 hex: '#111111' },
  22:  { name: 'Dino Dark Red',         hex: '#7F0000' },
  23:  { name: 'Dino Dark Orange',      hex: '#7F3F00' },
  24:  { name: 'Dino Dark Yellow',      hex: '#7F7F00' },
  25:  { name: 'Dino Dark Green',       hex: '#007F00' },
  26:  { name: 'Dino Dark Cyan',        hex: '#007F7F' },
  27:  { name: 'Dino Dark Blue',        hex: '#00007F' },
  28:  { name: 'Dino Light Red',        hex: '#FF6060' },
  29:  { name: 'Dino Light Orange',     hex: '#FFA040' },
  30:  { name: 'Dino Light Yellow',     hex: '#FFFF60' },
  31:  { name: 'Dino Light Green',      hex: '#60FF60' },
  32:  { name: 'Dino Light Cyan',       hex: '#60FFFF' },
  33:  { name: 'Dino Light Blue',       hex: '#6080FF' },
  34:  { name: 'Dino Medium Red',       hex: '#BF4040' },
  35:  { name: 'Dino Medium Orange',    hex: '#BF7F40' },
  36:  { name: 'Dino Medium Yellow',    hex: '#BFBF40' },
  37:  { name: 'Dino Medium Green',     hex: '#40BF40' },
  38:  { name: 'Dino Medium Cyan',      hex: '#40BFBF' },
  39:  { name: 'Dino Medium Blue',      hex: '#4060BF' },
  40:  { name: 'Dino Dark Purple',      hex: '#3F007F' },
  41:  { name: 'Dino Medium Purple',    hex: '#7F3FBF' },
  42:  { name: 'Dino Light Purple',     hex: '#BF60FF' },
  43:  { name: 'Dino Tan',              hex: '#BFBF80' },
  44:  { name: 'Dino Cream',            hex: '#FFFFBF' },
  45:  { name: 'Dino Dark Brown',       hex: '#3F2000' },
  46:  { name: 'Dino Medium Brown',     hex: '#7F4000' },
  47:  { name: 'Dino Light Brown',      hex: '#BF8040' },
  48:  { name: 'Dino Dark Pink',        hex: '#7F0040' },
  49:  { name: 'Dino Medium Pink',      hex: '#BF4080' },
  50:  { name: 'Dino Light Pink',       hex: '#FF80BF' },
  51:  { name: 'Dino Pale Green',       hex: '#80BF80' },
  52:  { name: 'Dino Pale Yellow',      hex: '#BFBF60' },
  53:  { name: 'Dino Light Blue',       hex: '#9BBEFF' },
  54:  { name: 'Dino Pale Blue',        hex: '#80A0BF' },
  55:  { name: 'Dino Navy Blue',        hex: '#203060' },
  56:  { name: 'Dino Aqua',             hex: '#40BFFF' },
  57:  { name: 'Dino Teal',             hex: '#208080' },
  58:  { name: 'Dino Olive',            hex: '#608020' },
  59:  { name: 'Dino Forest Green',     hex: '#206020' },
  60:  { name: 'Dino Lime',             hex: '#80FF20' },
  61:  { name: 'Dino Amber',            hex: '#FFC000' },
  62:  { name: 'Dino Gold',             hex: '#FFD700' },
  63:  { name: 'Dino Dark Gold',        hex: '#BFA020' },
  64:  { name: 'Dino Bronze',           hex: '#8B6914' },
  65:  { name: 'Dino Copper',           hex: '#B87333' },
  66:  { name: 'Dino Silver',           hex: '#C0C0C0' },
  67:  { name: 'Dino Platinum',         hex: '#E5E4E2' },
  68:  { name: 'Dino Charcoal',         hex: '#404040' },
  69:  { name: 'Dino Ash',              hex: '#808080' },
  70:  { name: 'Dino Snow',             hex: '#FFFAFA' },
  71:  { name: 'Dino Ivory',            hex: '#FFFFF0' },
  72:  { name: 'Dino Bone',             hex: '#E3DAC9' },
  73:  { name: 'Dino Rust',             hex: '#B7410E' },
  74:  { name: 'Dino Scarlet',          hex: '#FF2400' },
  75:  { name: 'Dino Crimson',          hex: '#DC143C' },
  76:  { name: 'Dino Rose',             hex: '#FF007F' },
  77:  { name: 'Dino Salmon',           hex: '#FA8072' },
  78:  { name: 'Dino Coral',            hex: '#FF7F50' },
  79:  { name: 'Dino Peach',            hex: '#FFDAB9' },
  80:  { name: 'Dino Apricot',          hex: '#FBCEB1' },
  81:  { name: 'Dino Pumpkin',          hex: '#FF7518' },
  82:  { name: 'Dino Sand',             hex: '#C2B280' },
  83:  { name: 'Dino Khaki',            hex: '#C3B091' },
  84:  { name: 'Dino Beige',            hex: '#F5F5DC' },
  85:  { name: 'Dino Wheat',            hex: '#F5DEB3' },
  86:  { name: 'Dino Lemon',            hex: '#FFF44F' },
  87:  { name: 'Dino Chartreuse',       hex: '#7FFF00' },
  88:  { name: 'Dino Mint',             hex: '#98FF98' },
  89:  { name: 'Dino Sage',             hex: '#BCB88A' },
  90:  { name: 'Dino Moss',             hex: '#8A9A5B' },
  91:  { name: 'Dino Fern',             hex: '#4F7942' },
  92:  { name: 'Dino Hunter Green',     hex: '#355E3B' },
  93:  { name: 'Dino Emerald',          hex: '#50C878' },
  94:  { name: 'Dino Jade',             hex: '#00A86B' },
  95:  { name: 'Dino Turquoise',        hex: '#40E0D0' },
  96:  { name: 'Dino Ice Blue',         hex: '#99C5C4' },
  97:  { name: 'Dino Powder Blue',      hex: '#B0E0E6' },
  98:  { name: 'Dino Cornflower',       hex: '#6495ED' },
  99:  { name: 'Dino Royal Blue',       hex: '#4169E1' },
  100: { name: 'Dino Midnight Blue',    hex: '#191970' },
  101: { name: 'Dino Indigo',           hex: '#4B0082' },
  102: { name: 'Dino Violet',           hex: '#8F00FF' },
  103: { name: 'Dino Lavender',         hex: '#E6E6FA' },
  104: { name: 'Dino Orchid',           hex: '#DA70D6' },
  105: { name: 'Dino Plum',             hex: '#DDA0DD' },
  106: { name: 'Dino Grape',            hex: '#6F2DA8' },
  107: { name: 'Dino Maroon',           hex: '#800000' },
  108: { name: 'Slate',                 hex: '#6D7B8D' },
  109: { name: 'Dino Steel Blue',       hex: '#4682B4' },
  110: { name: 'Dino Dusty Blue',       hex: '#7393B7' },
  111: { name: 'Dino Cobalt',           hex: '#0047AB' },
  112: { name: 'Dino Azure',            hex: '#F0FFFF' },
  113: { name: 'Dino Electric Blue',    hex: '#7DF9FF' },
  114: { name: 'Dino Neon Green',       hex: '#39FF14' },
  115: { name: 'Dino Neon Yellow',      hex: '#DFFF00' },
  116: { name: 'Dino Neon Orange',      hex: '#FF6103' },
  117: { name: 'Dino Neon Pink',        hex: '#FF10F0' },
  118: { name: 'Dino Neon Purple',      hex: '#CF00FF' },
  119: { name: 'Dino Neon Red',         hex: '#FF3131' },
  120: { name: 'Dino Neon Cyan',        hex: '#00FFEF' },
  121: { name: 'Wyvern Fire Red',       hex: '#CC2200' },
  122: { name: 'Wyvern Ice Blue',       hex: '#AADDFF' },
  123: { name: 'Wyvern Lightning',      hex: '#BBBBFF' },
  124: { name: 'Wyvern Poison Green',   hex: '#66BB00' },
  125: { name: 'Drake Blue',            hex: '#334488' },
  126: { name: 'Drake Purple',          hex: '#553366' },
  127: { name: 'Drake Green',           hex: '#225533' },
  128: { name: 'Drake Red',             hex: '#882211' },
  129: { name: 'Giga Dark Red',         hex: '#660000' },
  130: { name: 'Giga Orange',           hex: '#FF6600' },
  131: { name: 'Aberrant Violet',       hex: '#8833CC' },
  132: { name: 'Aberrant Teal',         hex: '#009977' },
  133: { name: 'Featherlight Gold',     hex: '#FFCC33' },
  134: { name: 'Bulbdog Blue',          hex: '#3399FF' },
  135: { name: 'Glowtail Pink',         hex: '#FF66AA' },
  136: { name: 'Dino Olive Drab',       hex: '#6B8E23' },
  137: { name: 'Dino Sepia',            hex: '#704214' },
  138: { name: 'Dino Taupe',            hex: '#8B7355' },
  139: { name: 'Dino Umber',            hex: '#635147' },
  140: { name: 'Dino Caramel',          hex: '#C68642' },
  141: { name: 'Dino Honey',            hex: '#FFB347' },
  142: { name: 'Dino Butterscotch',     hex: '#E3963E' },
  143: { name: 'Dino Peanut',           hex: '#B56917' },
  144: { name: 'Dino Chestnut',         hex: '#954535' },
  145: { name: 'Dino Mahogany',         hex: '#C04000' },
  146: { name: 'Dino Wine',             hex: '#722F37' },
  147: { name: 'Dino Burgundy',         hex: '#800020' },
  148: { name: 'Dino Cherry',           hex: '#DE3163' },
  149: { name: 'Dino Fuchsia',          hex: '#FF77FF' },
  150: { name: 'Dino Hot Pink',         hex: '#FF69B4' },
  186: { name: 'Dino Heliotrope',       hex: '#DF73FF' },
  187: { name: 'Dino Amethyst',         hex: '#9966CC' },
  216: { name: 'Aberrant Yellow',       hex: '#CCCC00' },
  221: { name: 'Extinction Copper',     hex: '#BB7733' },
  226: { name: 'Fjordur Purple',        hex: '#7733AA' },
  229: { name: 'Ragnarok Brown',        hex: '#885533' },
};

/** Convert a hex string to { r, g, b } (0–255 each). */
function hexToRgb(hex) {
  if (!hex) return { r: 0, g: 0, b: 0 };
  const c = hex.replace('#', '');
  return {
    r: parseInt(c.slice(0, 2), 16),
    g: parseInt(c.slice(2, 4), 16),
    b: parseInt(c.slice(4, 6), 16),
  };
}

/**
 * Find the nearest ARK color name for a given hex value.
 * Returns { id, name, hex } of the closest match.
 */
export function findNearestArkColor(hex) {
  if (!hex) return null;
  const { r: tr, g: tg, b: tb } = hexToRgb(hex);
  let best = null, bestDist = Infinity;
  for (const [id, color] of Object.entries(ARK_COLORS_FRONTEND)) {
    if (!color.hex) continue;
    const { r, g, b } = hexToRgb(color.hex);
    const dist = (r - tr) ** 2 + (g - tg) ** 2 + (b - tb) ** 2;
    if (dist < bestDist) {
      bestDist = dist;
      best = { id: parseInt(id), name: color.name, hex: color.hex };
    }
  }
  return best;
}
