/**
 * Frontend copy of the ARK Color ID → { name, hex } map.
 * Mirrors backend/colorMap.js for use in React without a server round-trip.
 */
export const ARK_COLORS_FRONTEND = {
  0:   { name: 'Unset',                    hex: null },
  1:   { name: 'Red',                      hex: '#FF0000' },
  2:   { name: 'Blue',                     hex: '#0000FF' },
  3:   { name: 'Green',                    hex: '#00FF00' },
  4:   { name: 'Yellow',                   hex: '#FFFF00' },
  5:   { name: 'Cyan',                     hex: '#00FFFF' },
  6:   { name: 'Magenta',                  hex: '#FF00FF' },
  7:   { name: 'Light Green',              hex: '#C0FFBA' },
  8:   { name: 'Light Grey',               hex: '#C8CACA' },
  9:   { name: 'Light Brown',              hex: '#786759' },
  10:  { name: 'Light Orange',             hex: '#FFB46C' },
  11:  { name: 'Light Yellow',             hex: '#FFFA8A' },
  12:  { name: 'Light Red',                hex: '#FF756C' },
  13:  { name: 'Dark Grey',                hex: '#7B7B7B' },
  14:  { name: 'Black',                    hex: '#3B3B3B' },
  15:  { name: 'Brown',                    hex: '#593A2A' },
  16:  { name: 'Dark Green',               hex: '#224900' },
  17:  { name: 'Dark Red',                 hex: '#812118' },
  18:  { name: 'White',                    hex: '#FFFFFF' },
  19:  { name: 'Dino Light Red',           hex: '#FFA8A8' },
  20:  { name: 'Dino Dark Red',            hex: '#592B2B' },
  21:  { name: 'Dino Light Orange',        hex: '#FFB694' },
  22:  { name: 'Dino Dark Orange',         hex: '#88532F' },
  23:  { name: 'Dino Light Yellow',        hex: '#CACAA0' },
  24:  { name: 'Dino Dark Yellow',         hex: '#94946C' },
  25:  { name: 'Dino Light Green',         hex: '#E0FFE0' },
  26:  { name: 'Dino Medium Green',        hex: '#799479' },
  27:  { name: 'Dino Dark Green',          hex: '#224122' },
  28:  { name: 'Dino Light Blue',          hex: '#D9E0FF' },
  29:  { name: 'Dino Dark Blue',           hex: '#394263' },
  30:  { name: 'Dino Light Purple',        hex: '#E4D9FF' },
  31:  { name: 'Dino Dark Purple',         hex: '#403459' },
  32:  { name: 'Dino Light Brown',         hex: '#FFE0BA' },
  33:  { name: 'Dino Medium Brown',        hex: '#948575' },
  34:  { name: 'Dino Dark Brown',          hex: '#594E41' },
  35:  { name: 'Dino Darker Grey',         hex: '#595959' },
  36:  { name: 'Dino Albino',              hex: '#FFFFFF' },
  37:  { name: 'BigFoot0',                 hex: '#B79683' },
  38:  { name: 'BigFoot4',                 hex: '#EADAD5' },
  39:  { name: 'BigFoot5',                 hex: '#D0A794' },
  40:  { name: 'WolfFur',                  hex: '#C3B39F' },
  41:  { name: 'DarkWolfFur',              hex: '#887666' },
  42:  { name: 'DragonBase0',              hex: '#A0664B' },
  43:  { name: 'DragonBase1',              hex: '#CB7956' },
  44:  { name: 'DragonFire',               hex: '#BC4F00' },
  45:  { name: 'DragonGreen0',             hex: '#79846C' },
  46:  { name: 'DragonGreen1',             hex: '#909C79' },
  47:  { name: 'DragonGreen2',             hex: '#A5A48B' },
  48:  { name: 'DragonGreen3',             hex: '#74939C' },
  49:  { name: 'WyvernPurple0',            hex: '#787496' },
  50:  { name: 'WyvernPurple1',            hex: '#B0A2C0' },
  51:  { name: 'WyvernBlue0',              hex: '#6281A7' },
  52:  { name: 'WyvernBlue1',              hex: '#485C75' },
  53:  { name: 'Dino Medium Blue',         hex: '#5FA4EA' },
  54:  { name: 'Dino Deep Blue',           hex: '#4568D4' },
  55:  { name: 'NearWhite',                hex: '#EDEDED' },
  56:  { name: 'NearBlack',                hex: '#515151' },
  57:  { name: 'DarkTurquoise',            hex: '#184546' },
  58:  { name: 'MediumTurquoise',          hex: '#007060' },
  59:  { name: 'Turquoise',                hex: '#00C5AB' },
  60:  { name: 'GreenSlate',               hex: '#40594C' },
  61:  { name: 'Sage',                     hex: '#3E4F40' },
  62:  { name: 'DarkWarmGray',             hex: '#3B3938' },
  63:  { name: 'MediumWarmGray',           hex: '#585554' },
  64:  { name: 'LightWarmGray',            hex: '#9B9290' },
  65:  { name: 'DarkCement',               hex: '#525B56' },
  66:  { name: 'LightCement',              hex: '#8AA196' },
  67:  { name: 'LightPink',                hex: '#E8B0FF' },
  68:  { name: 'DeepPink',                 hex: '#FF119A' },
  69:  { name: 'DarkViolet',               hex: '#730046' },
  70:  { name: 'DarkMagenta',              hex: '#B70042' },
  71:  { name: 'BurntSienna',              hex: '#7E331E' },
  72:  { name: 'MediumAutumn',             hex: '#A93000' },
  73:  { name: 'Vermillion',               hex: '#EF3100' },
  74:  { name: 'Coral',                    hex: '#FF5834' },
  75:  { name: 'Orange',                   hex: '#FF7F00' },
  76:  { name: 'Peach',                    hex: '#FFA73A' },
  77:  { name: 'LightAutumn',              hex: '#AE7000' },
  78:  { name: 'Mustard',                  hex: '#949427' },
  79:  { name: 'ActualBlack',              hex: '#171717' },
  80:  { name: 'MidnightBlue',             hex: '#191D36' },
  81:  { name: 'DarkBlue',                 hex: '#152B3A' },
  82:  { name: 'BlackSands',               hex: '#302531' },
  84:  { name: 'LemonLime',                hex: '#A8FF44' },
  85:  { name: 'Mint',                     hex: '#38E985' },
  86:  { name: 'Jade',                     hex: '#008840' },
  87:  { name: 'PineGreen',                hex: '#0F552E' },
  88:  { name: 'SpruceGreen',              hex: '#005B45' },
  89:  { name: 'LeafGreen',                hex: '#5B9725' },
  90:  { name: 'DarkLavender',             hex: '#5E275F' },
  91:  { name: 'MediumLavender',           hex: '#853587' },
  92:  { name: 'Lavender',                 hex: '#BD77BE' },
  93:  { name: 'DarkTeal',                 hex: '#0E404A' },
  94:  { name: 'MediumTeal',               hex: '#105563' },
  95:  { name: 'Teal',                     hex: '#14849C' },
  96:  { name: 'PowderBlue',               hex: '#82A7FF' },
  97:  { name: 'Glacial',                  hex: '#ACEAFF' },
  98:  { name: 'Cammo',                    hex: '#505118' },
  99:  { name: 'DryMoss',                  hex: '#766E3F' },
  100: { name: 'Custard',                  hex: '#C0BD5E' },
  128: { name: 'Burn Coloring',            hex: '#360000' },
  129: { name: 'Scab Coloring',            hex: '#660000' },
  130: { name: 'Gore Coloring',            hex: '#B20000' },
  131: { name: 'Red Coloring',             hex: '#FF0000' },
  132: { name: 'Tulip Coloring',           hex: '#FF7272' },
  133: { name: 'Salmon Coloring',          hex: '#FFBEBE' },
  134: { name: 'Incense Coloring',         hex: '#D88C8C' },
  135: { name: 'Edocha Coloring',          hex: '#A55454' },
  136: { name: 'Bronze Coloring',          hex: '#361F00' },
  137: { name: 'Terracotta Coloring',      hex: '#663600' },
  138: { name: 'Windsor Coloring',         hex: '#B25900' },
  139: { name: 'Orange Coloring',          hex: '#FF7E00' },
  140: { name: 'Cantaloupe Coloring',      hex: '#FFB872' },
  141: { name: 'Peach Coloring',           hex: '#FFDEBE' },
  142: { name: 'Latte Coloring',           hex: '#D8B28C' },
  143: { name: 'Dirt Coloring',            hex: '#A57B54' },
  144: { name: 'Drab Coloring',            hex: '#363600' },
  145: { name: 'Olive Coloring',           hex: '#666600' },
  146: { name: 'Citron Coloring',          hex: '#B1B200' },
  147: { name: 'Yellow Coloring',          hex: '#FFFF00' },
  148: { name: 'Canary Coloring',          hex: '#FFFF72' },
  149: { name: 'Buttermilk Coloring',      hex: '#FFFFBE' },
  150: { name: 'Khaki Coloring',           hex: '#D8D88C' },
  151: { name: 'Mold Coloring',            hex: '#A5A554' },
  152: { name: 'Swamp Coloring',           hex: '#1F3600' },
  153: { name: 'Avocado Coloring',         hex: '#366600' },
  154: { name: 'Orc Coloring',             hex: '#59B200' },
  155: { name: 'Chartreuse Coloring',      hex: '#7FFF00' },
  156: { name: 'Menthol Coloring',         hex: '#B8FF72' },
  157: { name: 'Nyanza Coloring',          hex: '#DEFFBE' },
  158: { name: 'Putrescence Coloring',     hex: '#B2D88C' },
  159: { name: 'Filth Coloring',           hex: '#7BA554' },
  160: { name: 'Nori Coloring',            hex: '#003600' },
  161: { name: 'Hunter Coloring',          hex: '#006600' },
  162: { name: 'Emerald Coloring',         hex: '#00B200' },
  163: { name: 'Green Coloring',           hex: '#00FF00' },
  164: { name: 'Mint Coloring',            hex: '#72FF72' },
  165: { name: 'Pistachio Coloring',       hex: '#BEFFBE' },
  166: { name: 'Celadon Coloring',         hex: '#8CD88C' },
  167: { name: 'Chateau Coloring',         hex: '#54A554' },
  168: { name: 'Jungle Coloring',          hex: '#003620' },
  169: { name: 'Forest Coloring',          hex: '#006636' },
  170: { name: 'Lagoon Coloring',          hex: '#00B259' },
  171: { name: 'Spring Coloring',          hex: '#00FF7F' },
  172: { name: 'Aquamarine Coloring',      hex: '#72FFB8' },
  173: { name: 'Seafoam Coloring',         hex: '#BEFFDE' },
  174: { name: 'Turquoise Coloring',       hex: '#8CD8B2' },
  175: { name: 'Shamrock Coloring',        hex: '#54A57B' },
  176: { name: 'Mariana Coloring',         hex: '#003636' },
  177: { name: 'Skobeloff Coloring',       hex: '#006666' },
  178: { name: 'Teal Coloring',            hex: '#00B2B2' },
  179: { name: 'Cyan Coloring',            hex: '#00FFFF' },
  180: { name: 'Electricity Coloring',     hex: '#72FFFF' },
  181: { name: 'Celeste Coloring',         hex: '#BEFFFF' },
  182: { name: 'Crystal Coloring',         hex: '#8CD8D8' },
  183: { name: 'Ocean Coloring',           hex: '#54A5A5' },
  184: { name: 'Cetecean Coloring',        hex: '#002036' },
  185: { name: 'Prussian Coloring',        hex: '#003666' },
  186: { name: 'Sapphire Coloring',        hex: '#0059B2' },
  187: { name: 'Azure Coloring',           hex: '#007EFF' },
  188: { name: 'Babyblue Coloring',        hex: '#72B8FF' },
  189: { name: 'Cornflower Coloring',      hex: '#BEDEFF' },
  190: { name: 'Overcast Coloring',        hex: '#8BB1D8' },
  191: { name: 'Moonstone Coloring',       hex: '#547BA5' },
  192: { name: 'Midnight Coloring',        hex: '#000036' },
  193: { name: 'Navy Coloring',            hex: '#000066' },
  194: { name: 'Cobalt Coloring',          hex: '#0000B2' },
  195: { name: 'Blue Coloring',            hex: '#0000FF' },
  196: { name: 'Denim Coloring',           hex: '#7272FF' },
  197: { name: 'Ice Coloring',             hex: '#BEBEFF' },
  198: { name: 'Frost Coloring',           hex: '#8B8BD8' },
  199: { name: 'Deepfreeze Coloring',      hex: '#5454A5' },
  200: { name: 'Twilight Coloring',        hex: '#1F0036' },
  201: { name: 'Eminence Coloring',        hex: '#360066' },
  202: { name: 'Indigo Coloring',          hex: '#5900B2' },
  203: { name: 'Violet Coloring',          hex: '#7F00FF' },
  204: { name: 'Lilac Coloring',           hex: '#B872FF' },
  205: { name: 'Lavender Coloring',        hex: '#DEBEFF' },
  206: { name: 'Mauve Coloring',           hex: '#B28CD8' },
  207: { name: 'Royalty Coloring',         hex: '#7B54A5' },
  208: { name: 'Eggplant Coloring',        hex: '#360036' },
  209: { name: 'Plum Coloring',            hex: '#660066' },
  210: { name: 'Purple Coloring',          hex: '#B100B2' },
  211: { name: 'Magenta Coloring',         hex: '#FF00FF' },
  212: { name: 'Pink Coloring',            hex: '#FF72FF' },
  213: { name: 'Cottoncandy Coloring',     hex: '#FFBEFF' },
  214: { name: 'Orchid Coloring',          hex: '#D88CD8' },
  215: { name: 'Bruise Coloring',          hex: '#A554A5' },
  216: { name: 'Raisin Coloring',          hex: '#36001F' },
  217: { name: 'Tyrian Coloring',          hex: '#660036' },
  218: { name: 'Lust Coloring',            hex: '#B20059' },
  219: { name: 'Fuschia Coloring',         hex: '#FF007E' },
  220: { name: 'Flamingo Coloring',        hex: '#FF72B8' },
  221: { name: 'Valentine Coloring',       hex: '#FFBEDE' },
  222: { name: 'Kobi Coloring',            hex: '#D88CB2' },
  223: { name: 'Rouge Coloring',           hex: '#A5547B' },
  224: { name: 'Black Coloring',           hex: '#1F1F1F' },
  225: { name: 'Shadow Coloring',          hex: '#363636' },
  226: { name: 'Charcoal Coloring',        hex: '#4E4E4E' },
  227: { name: 'Gunmetal Coloring',        hex: '#666666' },
  228: { name: 'Slate Coloring',           hex: '#7F7F7F' },
  229: { name: 'Steel Coloring',           hex: '#989898' },
  230: { name: 'Grey Coloring',            hex: '#B2B2B2' },
  231: { name: 'Silver Coloring',          hex: '#CBCBCB' },
  232: { name: 'Wisp Coloring',            hex: '#E6E6E6' },
  233: { name: 'White Coloring',           hex: '#FFFFFF' },
  234: { name: 'Mud Coloring',             hex: '#423726' },
  235: { name: 'Bark Coloring',            hex: '#594828' },
  236: { name: 'Brown Coloring',           hex: '#7F6430' },
  237: { name: 'Leather Coloring',         hex: '#98813F' },
  238: { name: 'Camel Coloring',           hex: '#B29B59' },
  239: { name: 'Tan Coloring',             hex: '#CBB166' },
  240: { name: 'Sand Coloring',            hex: '#E6C872' },
  241: { name: 'Parchment Coloring',       hex: '#FFEFBE' },
  242: { name: 'Cream Coloring',           hex: '#F5F5DB' },
  243: { name: 'Brick Coloring',           hex: '#98452A' },
  244: { name: 'Tangerine Coloring',       hex: '#FFA328' },
  245: { name: 'Gold Coloring',            hex: '#FFBF00' },
  246: { name: 'Mustard Coloring',         hex: '#B5A642' },
  247: { name: 'Craggy-Dew Coloring',      hex: '#6B7F6A' },
  248: { name: 'Grass Coloring',           hex: '#4CAF50' },
  249: { name: 'Stream Coloring',          hex: '#4DA6FF' },
  250: { name: 'Marine Coloring',          hex: '#003F5C' },
  251: { name: 'Haze Coloring',            hex: '#A0A0B2' },
  252: { name: 'Dusk Coloring',            hex: '#5A4E7A' },
  253: { name: 'Thistle Coloring',         hex: '#D8BFD8' },
  254: { name: 'Bubblegum Coloring',       hex: '#FF77AA' },
};

/**
 * Find the nearest ARK color entry for a given hex string.
 * Uses perceptual (weighted Euclidean) distance in sRGB space.
 */
export function findNearestArkColor(hex) {
  if (!hex) return null;
  const r1 = parseInt(hex.slice(1, 3), 16);
  const g1 = parseInt(hex.slice(3, 5), 16);
  const b1 = parseInt(hex.slice(5, 7), 16);

  let best = null, bestDist = Infinity;
  for (const [idStr, entry] of Object.entries(ARK_COLORS_FRONTEND)) {
    if (!entry.hex) continue;
    const r2 = parseInt(entry.hex.slice(1, 3), 16);
    const g2 = parseInt(entry.hex.slice(3, 5), 16);
    const b2 = parseInt(entry.hex.slice(5, 7), 16);
    const dr = r1 - r2, dg = g1 - g2, db = b1 - b2;
    // Weighted perceptual distance
    const dist = 2 * dr * dr + 4 * dg * dg + 3 * db * db;
    if (dist < bestDist) {
      bestDist = dist;
      best = { id: Number(idStr), name: entry.name, hex: entry.hex };
    }
  }
  return best;
}
